#!/bin/bash

echo "🚀 Déploiement Analytics en Production CapRover"
echo ""
echo "─────────────────────────────────────────────────"
echo "📋 ÉTAPES À SUIVRE:"
echo "─────────────────────────────────────────────────"
echo ""

echo "1️⃣  MIGRER LA BASE DE DONNÉES"
echo "   Se connecter au serveur PostgreSQL CapRover:"
echo ""
echo "   ssh root@votre-serveur"
echo "   docker exec -it \$(docker ps | grep postgres-monitoring | awk '{print \$1}') psql -U monitoring -d monitoring"
echo ""
echo "   Puis exécuter:"
echo "   CREATE TABLE IF NOT EXISTS \"AnalyticsEvent\" ("
echo "     \"id\" TEXT PRIMARY KEY,"
echo "     \"userId\" TEXT NOT NULL,"
echo "     \"eventType\" TEXT NOT NULL,"
echo "     \"metadata\" JSONB,"
echo "     \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP"
echo "   );"
echo ""
echo "   CREATE INDEX \"AnalyticsEvent_userId_idx\" ON \"AnalyticsEvent\"(\"userId\");"
echo "   CREATE INDEX \"AnalyticsEvent_eventType_idx\" ON \"AnalyticsEvent\"(\"eventType\");"
echo "   CREATE INDEX \"AnalyticsEvent_createdAt_idx\" ON \"AnalyticsEvent\"(\"createdAt\");"
echo ""
echo "─────────────────────────────────────────────────"
echo ""

echo "2️⃣  AJOUTER VARIABLES (Optionnel - pour PostHog)"
echo "   Dans CapRover App Config (movers-test):"
echo ""
echo "   NEXT_PUBLIC_POSTHOG_KEY=phc_xxx"
echo "   NEXT_PUBLIC_POSTHOG_HOST=https://app.posthog.com"
echo ""
echo "   (Créer compte gratuit sur https://app.posthog.com)"
echo ""
echo "─────────────────────────────────────────────────"
echo ""

echo "3️⃣  DÉPLOYER L'APP"
echo "   git push origin main  ✅ (déjà fait)"
echo ""
echo "   Puis dans CapRover:"
echo "   - Deployment → Deploy via ImageName"
echo "   - Ou attendre auto-deploy si configuré"
echo ""
echo "─────────────────────────────────────────────────"
echo ""

echo "4️⃣  TESTER LE DASHBOARD"
echo "   curl https://movers-test.gslv.cloud/api/analytics/dashboard | jq"
echo ""
echo "   Ou dans le navigateur:"
echo "   https://movers-test.gslv.cloud/api/analytics/dashboard"
echo ""
echo "─────────────────────────────────────────────────"
echo ""

echo "✅ Une fois déployé, les événements seront trackés automatiquement !"
echo ""

